spring:
  datasource:
    url: jdbc:mysql://localhost/mercado_livre
    username: root
    password: 2002
    driverClassName: com.mysql.jdbc.Driver

  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true

mercadolivre:
  jwt:
    expiration: 86400000
    secret: o78$4FUbcz!%#BOb52XskJ28j8H!!LTZlF^bZB#rye@$MeqJT$V$7TT1bYf@m#CV